FROM python:latest

WORKDIR /app

COPY python-practice.py python-practice.py

COPY colorama_proj.py colorama_proj.py

RUN pip install colorama

CMD python3 python-practice.py

#CMD python3 colorama_proj.py < 1
#CMD python3 colorama_proj.py < 2
